name: Blacksmith - Test Runner

on:
  workflow_dispatch:
  pull_request:

jobs:
  run-source-postgres-build:
    runs-on: buildjet-16vcpu-ubuntu-2204
    name: Build source-postgres
    timeout-minutes: 30
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Install Pip
        run: curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3
      - name: Install Pyenv
        run: python3 -m pip install virtualenv --user
      - name: Docker login
        # Some tests use testcontainers which pull images from DockerHub.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build source-postgres
        run: CI=true ./gradlew --scan --no-daemon --no-watch-fs :airbyte-integrations:connectors:source-postgres:check
